name: Build Nebula Client

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B build -A x64

    - name: Build Project
      run: cmake --build build --config Release

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Nebula-Client-Files
        path: |
          build/Release/NebulaInjector.exe
          build/Release/NebulaClient.dll
          
